server:
  port: 8081
spring:
  applications:
    name: config-test

  datasource:
    url: jdbc:mysql://localhost:3306/petclinic_msa
    username: root
    password: dkrakek1
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

    show-sql: true
    format-sql: true
