server:
  port: 8081

spring:
  application:
    name: reservation-service

  r2dbc:
    url: r2dbc:mysql://localhost:3306/petclinic_msa
    username: root
    password: dkrakek1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  show-sql: true
  format-sql: true
